### ISSUE TITLE
Can not run Simplest.py in my Macbook 2020 (Core i7)

### ISSUE THREAD

**Issue by kalmenchia** [Embarcadero/DelphiFMX4Python#11]
Hi , 

i have installed the delphifmx as shown,
<img width="976" alt="image" src="https://user-images.githubusercontent.com/1855737/153969078-25bf36a8-489f-4d1a-83db-6f071c6391b0.png">

and tried to run the sample as shown,
<img width="978" alt="image" src="https://user-images.githubusercontent.com/1855737/153969138-63e09c1a-c63e-4580-9c69-61b929fe7038.png">

but ran into some could not open DLL "libpython3.7.dylib" issues, any advice please ? 
thanks.

**Comment by lmbelo** [comment]
Hi @kalmenchia,

most probably because your Python's distribution doesn't provide the interpreter shared library. I'd suggest the Python's standard installation, downloaded from the [Python ](https://www.python.org/downloads/macos/) website.

**Comment by jimmckeeth** [comment]
Let us know if reinstalling Python as Lucas suggested helps....

**Comment by kalmenchia** [comment]
Hi Jim, thanks for the Delphi 27 Anniversary presentation what a journey for me from D1 till D10.4 as well... ok, i installed as advice by Lucas but i cannot get the demo to run, it freeze , no error message, nothing, not sure what happened ...  by the way i have been using python for quite a while and will love to see this project take off !

<img width="982" alt="image" src="https://user-images.githubusercontent.com/1855737/154378265-01897150-ae20-4a9d-ac6e-e63480e615f0.png">

After i installed python3.79 , i uninstall delphifmx and reinstall it back as shown in the picture, tried at the python console to import delphifmx , no issues, but when i tries to run the sample ControlDesktop, it freezed !

pls advice, thanks all.

**Comment by lmbelo** [comment]
Hmm...I think I know what is happening. Does the launcher icon pops up on the dock?

**Comment by kalmenchia** [comment]
Lucas, exactly ... i need to kill it... in order to stop .

**Comment by kalmenchia** [comment]
Hi Lucas, may I check is any solution? thanks.

**Comment by lmbelo** [comment]
Hi, @kalmenchia! We are scheduling a new release for tomorrow. I will let you know for any news.

**Comment by kalmenchia** [comment]
Thanks. @lmbelo , Lucas.

**Comment by lmbelo** [comment]
@kalmenchia can you try again, please? Let me know if you run into new errors.
This issue will remain open still we have a confirmation.

**Comment by lmbelo** [comment]
> 

The delphifmx library now supports Conda and Venv on macOS.

**Comment by lmbelo** [comment]
> Hi @kalmenchia,
> 
> most probably because your Python's distribution doesn't provide the interpreter shared library. I'd suggest the Python's standard installation, downloaded from the [Python ](https://www.python.org/downloads/macos/) website.

The delphifmx library now supports Conda and Venv on macOS.

**Comment by kalmenchia** [comment]
Hi @lmbelo , 

I am using Python 3.7.9 , I have followed the download Pkg, and installed the Python 3.7.9 on Aug 17. 2020 but still the same result. I think it may be my current Python 3.7.9 is corrupted or some other reasons, I found after upgrading to my Macbook to the 2020 i7 recently, somehow my Venv did not work correctly, I had to manually copy some files from my existing notebook. Cut long story short, i run in my VM windows environment, python 3.7.4 , it works. But will come back next round for my Mac setting. although I wish to do the development without using VM in my Mac Env. , but I guess not this round. thanks for all the help Lucas.

**Comment by lmbelo** [comment]
Weird, it should work on our last release. 
Let me know if we can do something else.

**Comment by lmbelo** [comment]
> Hi @lmbelo ,
> 
> I am using Python 3.7.9 , I have followed the download Pkg, and installed the Python 3.7.9 on Aug 17. 2020 but still the same result. I think it may be my current Python 3.7.9 is corrupted or some other reasons, I found after upgrading to my Macbook to the 2020 i7 recently, somehow my Venv did not work correctly, I had to manually copy some files from my existing notebook. Cut long story short, i run in my VM windows environment, python 3.7.4 , it works. But will come back next round for my Mac setting. although I wish to do the development without using VM in my Mac Env. , but I guess not this round. thanks for all the help Lucas.

Can you try it under Conda env?

**Comment by kalmenchia** [comment]
HI @lmbelo ,

Sure, i have installed the latest miniconda , Miniconda3-latest-MacOSX-x86_64 ,but how do i install the delphifmx conda ?

I tried , #conda install delphifmx in my terminal , this is what i got
![image](https://user-images.githubusercontent.com/1855737/157347803-18d6f779-b998-4860-a120-6359203b97ef.png)


and i have checked  the conda repo , delphifmx is also not there, pls advice, thanks.

**Comment by Priyatham10** [comment]
@kalmenchia You can directly install using `pip` inside conda. we don't have `delphifmx` available to conda-forge yet. Please just run `pip install delphifmx` inside the conda environment. You'll be good to go.

**Comment by kalmenchia** [comment]
Hi @Priyatham10 ,

thanks , it works,

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/1855737/157357358-202c9206-8e17-472f-8d3b-aecaba96994c.png">

**Comment by Priyatham10** [comment]
> Hi @Priyatham10 ,
> 
> thanks , it works,

Great, it worked for you finally. Please feel free to post further issues you might face as you try building applications.
