### ISSUE TITLE
Is it working for Ubuntu?

### ISSUE THREAD

**Issue by zwm88** [Embarcadero/DelphiFMX4Python#18]
DelphiFMX works great on Windows, but not on Ubuntu.  I tried Python 3.8, 3.9 and 3.10 on two different Ubuntu 20.04 machines, the "import delphifmx" simply shows "Segmentation Fault".  Did I miss anything?

![image](https://user-images.githubusercontent.com/1857661/160487720-2e266900-8742-475e-9f70-35998696f599.png)

**Comment by lmbelo** [comment]
@zwm88 how have you installed Python? The Python version provided by apt-get is not supported, once it doesn't provide access to the C API symbols.

**Comment by zwm88** [comment]
Yes, I used "sudo apt install python3.10" to install the Python.  
Now I installed python3.10-dev and python3.10-full, the error was different:
![image](https://user-images.githubusercontent.com/1857661/160721344-21df532f-9606-46bb-8be1-d8ecd8a7c172.png)

**Comment by lmbelo** [comment]
Try to install from the official website:
https://www.python.org/downloads/

**Comment by zwm88** [comment]
Cool!  After recompiling the Python from the source, all samples worked like a charm.  Thanks, Imbelo.

**Comment by lmbelo** [comment]
@zwm88 I'm glad it worked out :D
