### ISSUE TITLE
OnKeyUp Error: No Registered EventHandler for events of type "TKeyEvent

### ISSUE THREAD

**Issue by knietsch** [Embarcadero/DelphiFMX4Python#25]
![Test_Exporter_py_](https://user-images.githubusercontent.com/69752231/166150727-bb3bdeb1-14c8-47fe-a1b2-1b8cc82ae84c.png)

![Delphi_](https://user-images.githubusercontent.com/69752231/166150692-ddf9c7ad-6b87-4423-b90d-755285e44438.png)

I made just a simple project in Delphi fmx and used the Exporter to Python. Delphi works perfect. When running without modification the Unit.py it get this Error. The same configuration in vcl runs perfect.
[Unit1.py.txt](https://github.com/Embarcadero/DelphiFMX4Python/files/8599139/Unit1.py.txt)

**Comment by lmbelo** [comment]
Hi @knietsch,

thank you for the feedback.

The issue you faced is due to a missed event handler. I will include it to be released in the next release.

I will let you know when it is available.

🚀

**Comment by knietsch** [comment]
thx a lot

**Comment by lmbelo** [comment]
@knietsch,
we just launched a new version with a fix to this issue. Can you try again, please?

**Comment by knietsch** [comment]
Well done. Works identically as in Delphi and delphivcl, so far i tested. 👍
