### ISSUE TITLE
Any document? Tutorials?

### ISSUE THREAD

**Issue by AllenDang** [Embarcadero/DelphiFMX4Python#3]
It's very exciting to see this news! I'm eager to put my hands on it. Where can I find related documentation? Tutorials maybe?

**Comment by lmbelo** [comment]
Hi, @AllenDang. 
Thanks for your interest. It's really exciting : )

We're working in a couple of demos and documentations enhancements. 
Fell free to give us any suggestions.

**Comment by AllenDang** [comment]
@lmbelo I tried to run sample on my M1 macbook, and got following error.
```sh
❯ python3 -m venv ~/SDK/pyenv-delphi
❯ source ~/SDK/pyenv-delphi/bin/activate
❯ pip install delphifmx
Collecting delphifmx
  Downloading delphifmx-0.1.30-cp39-cp39-macosx_11_0_arm64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 304 kB/s
Installing collected packages: delphifmx
Successfully installed delphifmx-0.1.30
❯ cd Downloads
❯ git clone https://github.com/Embarcadero/DelphiFMX4Python
Cloning into 'DelphiFMX4Python'...
remote: Enumerating objects: 720, done.
remote: Counting objects: 100% (263/263), done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 720 (delta 128), reused 154 (delta 78), pack-reused 457
Receiving objects: 100% (720/720), 167.28 MiB | 1.75 MiB/s, done.
Resolving deltas: 100% (290/290), done.
❯ cd DelphiFMX4Python
❯ cd samples/ControlsDesktop
❯ ls
controlsdemo.py readme.md
❯ python controlsdemo.py
Traceback (most recent call last):
  File "/Users/allen/Downloads/DelphiFMX4Python/samples/ControlsDesktop/controlsdemo.py", line 12, in <module>
    from delphifmx import *
  File "/Users/allen/SDK/pyenv-delphi/lib/python3.9/site-packages/delphifmx/__init__.py", line 82, in <module>
    package = new_import()
  File "/Users/allen/SDK/pyenv-delphi/lib/python3.9/site-packages/delphifmx/__init__.py", line 72, in new_import
    ld = loader.create_module(spec)
ImportError: dlopen(/Users/allen/SDK/pyenv-delphi/lib/python3.9/site-packages/delphifmx/OSXARM64/libDelphiFMX.dylib, 0x0002): tried: '/Users/allen/SDK/pyenv-delphi/lib/python3.9/site-packages/delphifmx/OSXARM64/libDelphiFMX.dylib' (code signature in <2D627531-CB8E-3D97-BE24-3045066492E7> '/Users/allen/SDK/pyenv-delphi/lib/python3.9/site-packages/delphifmx/OSXARM64/libDelphiFMX.dylib' not valid for use in process: Trying to load an unsigned library), '/usr/local/lib/libDelphiFMX.dylib' (no such file), '/usr/lib/libDelphiFMX.dylib' (no such file)
```

I can find `Users/allen/SDK/pyenv-delphi/lib/python3.9/site-packages/delphifmx/OSXARM64/libDelphiFMX.dylib` is presented.

![截屏2022-01-13 下午9 30 43](https://user-images.githubusercontent.com/18550/149339305-4f7d7f40-9938-4f80-9ca3-1a4b599970e8.png)

**Comment by lmbelo** [comment]
Hi, @AllenDang. I've just released a M1 supported version.
Fell free to try it out and report any issues or enhancements.

**Comment by AllenDang** [comment]
@lmbelo I cannot run ~/DephiFMX4Python/samples/Simplest.py. It will stuck after `python Simplest.py` forever.
Here is my env:
```sh
❯ pip list
Package    Version
---------- -------
delphifmx  0.1.33
pip        21.3.1
setuptools 59.0.1
```

**Comment by lmbelo** [comment]
@AllenDang I have the same report from another user. I'll try some workaround it.

**Comment by lmbelo** [comment]
@AllenDang which OS version are you using?

**Comment by AllenDang** [comment]
@lmbelo macOS 12.1

**Comment by Priyatham10** [comment]
We shall provide Tutorials to get started in the wiki page for now. We're working on creating extensive documentations. Will come up with any of the updates on the documentation and tutorials..

**Comment by Priyatham10** [comment]
Please check the Quick start guide on the wiki page here: https://github.com/Embarcadero/DelphiFMX4Python/wiki/Quick-start-guide. @AllenDang We're working on ideas around full-blown documentation that includes these and other tutorials and full API references. Please star and watch our project for future exciting news. We planned for a live stream on June 2nd with many announcements. Register for it at: https://attendee.gotowebinar.com/register/3633463041072258318?source=github
