### ISSUE TITLE
SystemError: <built-in method LoadProps of Parent_Form object at 0x0000021BF049DE50> returned NULL without setting an error

### ISSUE THREAD

**Issue by jamilygo** [Embarcadero/DelphiFMX4Python#39]
self.LoadProps(os.path.join(os.path.dirname(os.path.abspath(__file__)), "parent_window.pyfmx"))
SystemError: <built-in method LoadProps of Parent_Form object at 0x0000021BF049DE50> returned NULL without setting an error

vironment
SystemError: <built-in method LoadProps of Parent_Form object at 0x0000021BF049DE50> returned NULL without setting an error
delphi 11
windows 11
pyscrit 4.1.1.0 x64

**Comment by lmbelo** [comment]
Can you share your project? I can try to help.

**Comment by jamilygo** [comment]
below is some python code Export from delphi 11 ,only put a button on the delphi form
at the line occ the error
self.LoadProps(os.path.join(os.path.dirname(os.path.abspath(__file__)), "parent_window.pyfmx"))

import os
from delphifmx import *

class Parent_Form(Form):

    def __init__(self, owner):
        self.my_button = None
        self.enter_text_edit = None
        self.enter_text_label = None
        self.main_heading = None
        self.LoadProps(os.path.join(os.path.dirname(os.path.abspath(__file__)), "parent_window.pyfmx"))

    def my_buttonClick(self, Sender):
        pass

def main():
    Application.Initialize()
    Application.Title = 'Parent Window'
    Application.MainForm = Parent_Form(Application)
    Application.MainForm.Show()
    Application.Run()
    Application.MainForm.Destroy()

if __name__ == '__main__':
    main()

**Comment by Priyatham10** [comment]
You should have the `parent_window.pyfmx` in the same folder as the above python code script file. It returned `NULL` because the you might've relocated or deleted the `.pyfmx` form file.

**Comment by jamilygo** [comment]
I reWrite the code.Check
Not the problem, I confirm the *.py *.pyfmx, and I add try ... except pass round the error code line . It works, but not well

import os
import sys
from delphifmx import *

class Form2(Form):

    def __init__(self, owner):
        self.Button1 = None
        try:
            self.LoadProps(os.path.join(os.path.dirname(os.path.abspath(__file__)), "Unit2.pyfmx"))
        except:
            pass

def main():
    # Confirm the .py and .pyfmx file is or not in the same Dir
    fname = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Unit2.pyfmx")
    print(fname)
    print (os.path.isfile(fname))
    print(sys.argv[0])

    Application.Initialize()
    Application.Title = 'Form2'
    Application.MainForm = Form2(Application)
    Application.MainForm.Show()
    Application.Run()
    Application.MainForm.Destroy()

if __name__ == '__main__':
    main()

**Comment by Priyatham10** [comment]
I understood your error exactly. I just reproduced you error. See here:
![PyScripter_zip_error](https://user-images.githubusercontent.com/17174106/185898060-af41c2aa-fe0b-4a3a-8b85-9d49d5ba94ff.png)

This is because, you downloaded  the zip folder and didn't extracted the zip folder and trying to run the code inside zip folder. Extract the zip folder and run the code and you'll get the GUI window output.

**Comment by Priyatham10** [comment]
Did you get the issue resolved with the above reply @jamilygo ?

**Comment by jamilygo** [comment]
not the problem 
the program not in a zip file
*.py and *.pyfmx in the same folder

**Comment by jamilygo** [comment]
[The Share code file]
https://github.com/jamilygo/TestdelphilFMX-Export-to-Python

**Comment by jamilygo** [comment]
I found the bug , it's my fault, I put the program into a directory ,its path has Chinese Char. put it into All English or alb char ，Run...
ha ha ha

**Comment by jamilygo** [comment]
yes, I got it!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月23日(星期二) 上午7:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Embarcadero/DelphiFMX4Python] SystemError: <built-in method LoadProps of Parent_Form object at 0x0000021BF049DE50&gt; returned NULL without setting an error (Issue #39)





 
Did you get the issue resolved with the above reply @jamilygo ?
