### ISSUE TITLE
source code of DelphiFMX.pyd

### ISSUE THREAD

**Issue by hanlaohan** [Embarcadero/DelphiFMX4Python#44]
Delphi has always been released with source code, which is great. Once my project has problems, I can check the source code to determine how to solve them. 
However, I haven't found the source code of DelphiFMX.pyd, so any small problems in it will stop my project. Can release the source code of DelphiFMX.pyd?

**Comment by Priyatham10** [comment]
DelphiFMX4Python is powered by **Python4Delphi(P4D)**. `DelphiFMX.pyd` is a binary extension module created using **P4D**. The project file (`DelphiFMX.dproj`) used to create the `DelphiFMX.pyd`  is found at: https://github.com/Embarcadero/python4delphi/tree/master/Modules/DelphiFMX

And it's source code to create the module is present at: https://github.com/Embarcadero/python4delphi/tree/master/Source

**Comment by hanlaohan** [comment]
Thank you very much. In this way, my project may continue

**Comment by lmbelo** [comment]
Share your new features, by creating pull requests, whenever you think it fits these projects :D
