### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by shineworld** [Embarcadero/DelphiFMX4Python#48]
Hi,
I'm moving projects to Python 3.11.1 in which I use DelphiVCL4Python/DelphiFMX4Python so to use new python language performances improvements.

They seems do not cover yet Python 3.11 but Python4Delphi does.

There is any planning to support Python 3.11 ?

**Comment by lmbelo** [comment]
Hi @shineworld,

We're releasing a new version of both libraries with Python 3.11 support included.

**Comment by black-hat-shadow** [comment]
print(5+5)

**Comment by aveekbhat** [comment]
> Hi @shineworld,
> 
> We're releasing a new version of both libraries with Python 3.11 support included.

has this been released yet ? 
as in  the v0.1.51 i am still getting the following error
delphifmx.PyVerNotSupported: DelphiFMX doesn't support Python3.11.

**Comment by shineworld** [comment]
I guess you have to check (I do every day) the https://pypi.org/project/delphifmx/ repository.
The current delphifmx 0.1.51 support Python cp3.6 to cp3.10.

**Comment by shaunroselt** [comment]
Any update on this?

<img width="631" alt="image" src="https://user-images.githubusercontent.com/5418178/221397746-78b5cb71-04a2-4415-a776-dc77d3f86b70.png">

**Comment by lmbelo** [comment]
Hi everyone,
we have added support to cp3.11, but we didn't release it yet. We have included docs, other features and fixed bugs.
I will let you guys to known when it comes available.

**Comment by Priyatham10** [comment]
Hi everyone,
We have Python 3.11 support availability in our latest release. Please install the latest version of DelphiFMX..

**Comment by aveekbhat** [comment]
Thanks  !!  installed, it works !!

**Comment by shineworld** [comment]
Amazing JOB to all DelphiVCL/FMX contributors.

**Comment by Priyatham10** [comment]
Hi all, 
We've published a new blog post on this update. Please check out at: https://pythongui.org/introducing-python-3-11-and-documentation-support-to-the-delphifmx-and-delphivcl-gui-python-packages/
