### ISSUE TITLE
Product (package) names.

### ISSUE THREAD

**Issue by pauljurczak** [Embarcadero/DelphiFMX4Python#49]
I just fund about this new GUI library for Python and my first impression, before even getting to technical details, is a bewildering list of names: DelphiFMX for Python (DelphiFMX4Python), FireMonkey, PythonFMXBuilder and Python4Delphi. Is there an explanation somewhere for a person like me, who last heard of Delphi a decade or two ago and doesn't know the recent history of it?

**Comment by pauljurczak** [comment]
Reading the ebook "Getting Started with Python GUI Development" clears most of the confusion.

**Comment by shaunroselt** [comment]
I actually personally think "Delphi" should be dropped from the name. It shouldn't be called "DelphiFMX" or "DelphiFMX4Python".

I think it should just be called "FMX" or "FireMonkey". Maybe "FireMonkey for Python", but that feels a bit long.


I think it's simple. We have the FireMonkey framework and it's available for Delphi, C++ Builder, and Python. Same framework, but different languages.

**Comment by shaunroselt** [comment]
@Priyatham10 My reasoning for why it should drop the "Delphi" prefix is that I think this library can stand strong on its own. It's super powerful.

Having the "Delphi" prefix there is also very confusing to people who don't know Delphi or haven't heard of it in a long time.

Maybe what this library needs in the very long run is a GUI Form Builder outside of Delphi as a standalone app 🤷🏻‍♂️. That would be very cool! A `FireMonkey Form Builder` App 😁

**Comment by lmbelo** [comment]
> @Priyatham10 My reasoning for why it should drop the "Delphi" prefix is that I think this library can stand strong on its own. It's super powerful.
> 
> Having the "Delphi" prefix there is also very confusing to people who don't know Delphi or haven't heard of it in a long time.
> 
> Maybe what this library needs in the very long run is a GUI Form Builder outside of Delphi as a standalone app 🤷🏻‍♂️. That would be very cool! A `FireMonkey Form Builder` App 😁

The [PythonFMXBuilder](https://github.com/Embarcadero/PythonFMXBuilder) can be used to support such features.

**Comment by Priyatham10** [comment]
> Reading the ebook "Getting Started with Python GUI Development" clears most of the confusion.

@pauljurczak  and @shaunroselt We're also releasing the official docs of the packages in this week for the reference of all available types and their attributes.

**Comment by shaunroselt** [comment]
> Reading the ebook "Getting Started with Python GUI Development" clears most of the confusion.

@pauljurczak Could you post a link to this ebook please?

**Comment by pauljurczak** [comment]
@shaunroselt https://lp.embarcadero.com/PythonGUIgettingStarted
