### ISSUE TITLE
Form BorderIcons property not working

### ISSUE THREAD

**Issue by shaunroselt** [Embarcadero/DelphiFMX4Python#54]
How does the `BorderIcons` property work?

I have this code:
``` Python
from delphifmx import *

class frmMain(Form):
    def __init__(self, owner):
        self.Caption = 'My Form'
        self.Width = 1000
        self.Height = 500
        self.BorderStyle = "Single"
        self.BorderIcons = "[biSystemMenu,biMinimize]"

def main():
    Application.Initialize()
    Application.Title = "My Application"
    Application.MainForm = frmMain(Application)
    Application.MainForm.Show()
    Application.Run()
    Application.MainForm.Destroy()

main()
```

Basically what I want to do is disable the Maximize button in Title Bar. 

When I use `self.BorderIcons = ""` then there aren't any icons on the title bar which is what you would expect:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/5418178/221689749-78911042-91f2-4950-93ba-eea3c6abbb21.png">

But then when using `self.BorderIcons = "[biSystemMenu,biMinimize]"` I would expect to to see only close and minimize, but rather I see Maximize also and Maximize even works:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/5418178/221689979-c4dcf3d8-54d2-4b1d-af9c-26dfc516f2db.png">

Seems like this could be a bug or am I doing it wrong?

**Comment by lmbelo** [comment]
@shaunroselt it must be an array of strings. See the tip bellow:

`self.BorderIcons = ["biSystemMenu", "biMinimize"]`

**Comment by shaunroselt** [comment]
That works. Thank you!
