### ISSUE TITLE
Add TPopUpMenu

### ISSUE THREAD

**Issue by shaunroselt** [Embarcadero/DelphiFMX4Python#57]
I tried creating a `PopUpMenu `for one of my apps but seems like there isn't a wrapper for the `PopUpMenu` yet.

Are there any plans to add the PopUpMenu? Would really like to be able to have a PopUpMenu in my apps.

Is there maybe a tutorial or something around that can teach me how to make my own wrapper for a component?

**Comment by Priyatham10** [comment]
Hi @shaunroselt,  we just added it to the backlog of the roadmap. We can try to wrap it and provide it as part of the following docs release version.

**Comment by Priyatham10** [comment]
And also, there is a recent idea to create a youtube channel around our Delphi-Python Ecosystem. We plan to make tutorials on developing small to large-scale GUI applications using our Python packages. We also plan to create a tutorial to wrap any missing component by the community themselves.

**Comment by shaunroselt** [comment]
Thanks.

That's good to hear. I'm also planning lots of YouTube videos around this.

**Comment by lmbelo** [comment]
Adding TPopUpMenu to the roadmap.

**Comment by lmbelo** [comment]
Actually it has been wrapped before. See the image below:


![Screenshot 2023-03-06 at 16 48 54](https://user-images.githubusercontent.com/8376898/223215361-fc5e233d-f202-441d-a090-d94162d0463e.png)

**Comment by shaunroselt** [comment]
Oh. I see my fault. I tried doing:

`self.myPopUpMenu = PopUpMenu(self)`

Which doesn't work. It needs to be:

`self.myPopUpMenu = PopupMenu(self)`

**Comment by shaunroselt** [comment]
Thanks!

**Comment by lmbelo** [comment]
Sorry, I posted a VCL sample but it shall work with FMX too.
