### ISSUE TITLE
How do I change the cursor of a component?

### ISSUE THREAD

**Issue by shaunroselt** [Embarcadero/DelphiFMX4Python#59]
I've created an [FMX GUI App][1] and I have several components on the form. I'd like to change the default `Cursor` for them, but I'm not sure how.

I've tried doing the following code to change the `Cursor` on my `Memo`:
``` Python
self.Memo1.Cursor = "crNo"
```
But `self.Memo1.Cursor = "crNo"` doesn't work. I get `Error: Invalid class typecast`

What is the correct way to change the `Cursor` of a component?

  [1]: https://github.com/Embarcadero/DelphiFMX4Python

**Comment by lmbelo** [comment]
Actually "crNo" is a constant, not an enumeration. We must include the "Cursor" constants to the wrapper list.

**Comment by shaunroselt** [comment]
Thanks. 

So changing the `Cursor` isn't possible with the current version yet?

**Comment by Priyatham10** [comment]
Yes, Shaun. We currently have a few constants available in which `Cursor` constants are not yet available. For example, you're able to use the `Align` constants which are already wrapped. We shall soon wrap them.

**Comment by Priyatham10** [comment]
@shaunroselt We have this working in the new latest release. Please check and close the issue.

**Comment by shaunroselt** [comment]
@Priyatham10 Thanks. It works now. I tested it with the following code and it works:
```
self.Memo1 = Memo(self)
self.Memo1.Parent = self
self.Memo1.Align = "Client"

self.Memo1.Cursor = crNo
```

I also answered it on this StackOverflow question: https://stackoverflow.com/a/76279865/2908017

**Comment by Priyatham10** [comment]
Great to know that. @shaunroselt are you okay to take a session in the upcoming Python GUI Apps Conference on June 14-15?
