### ISSUE TITLE
Linux Issues with sample scripts

### ISSUE THREAD

**Issue by mvdw73** [Embarcadero/DelphiFMX4Python#69]
Trying to run the sample scripts from the command line gives an error "from: command not found". This is because running from the command line attempts to run the file as a shell script - linux ignores the extension (so-called "magic number), and instead relies on a shebang comment at the head of the script to determine the correct interpreter to run the script with.

This can be fixed by adding a line at the top of every sample as follows:

#!/usr/bin/env python3
 
I'm not putting in a PR because the samples also segfault for me under linux (see comment in issue #40); when that is fixed I will make a PR to fix this issue.

**Comment by mvdw73** [comment]
I've made a PR to fix this problem. It should be open for review.

**Comment by Priyatham10** [comment]
Sure @mvdw73 . Thank you. Will take a look into it.
