### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by limelect** [Embarcadero/DelphiFMX4Python#74]
Python36-32
window 7

pip install delphifmx

Collecting delphifmx
  Using cached https://files.pythonhosted.org/packages/55/64/fd1320a25a8cac3b39aa60b55998944bcebd5194b9e52ee9b8d8e7072f87/delphifmx-0.1.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\limelect\appdata\local\temp\pip-build-b79gbo\delphifmx\setup.py", line 49
        pyversionstrshort = f"{sys.version_info.major}{sys.version_info.minor}"
                                                                              ^
    SyntaxError: invalid syntax

**Comment by Priyatham10** [comment]
Hi @limelect,

You've already installed delphifmx when it was at `0.1.12` version. So, it was just collecting the cached existing installation in your computer. Try this command instead: `pip install -U delphifmx==1.0.6" and it'll hopefully install successfully.

**Comment by limelect** [comment]
first, I tried your suggestion pip install -U delphifmx==1.0.6" it cannot find this version

I tried with GuiPy to run G:\1\Delphi\Getting_Started_with_Python_GUI_Development-2.1\PythonFMXBuilder\Tip_Calculator_Python\Export_Entire_Current_Project

obviously, it could not find from delphifmx import *
so nothing is installed
so I am stack

**Comment by limelect** [comment]
The error is syntax error

SyntaxError: invalid syntax

**Comment by Priyatham10** [comment]
> pip install -U delphifmx==1.0.6

I think this should work. Please share screenshots when it says that it cannot find this version. And also, share screenshots of `pip show delphifmx`.  Are you using the Python installation in the system path or in conda?

**Comment by limelect** [comment]
Thank you
I found all my problems
It was Anaconda 2.6. I moved to 3.8 (win7) and changed the path environment
It took a wile but it run
