### ISSUE TITLE
DelphiFMX StringGrid Missing Cells?

### ISSUE THREAD

**Issue by FMXExpress** [Embarcadero/DelphiFMX4Python#79]
Trying to use StringGrid. No Cells property.

dir(delphifmx.StringGrid)
['AbsoluteClipRect', 'AbsoluteEnabled', 'AbsoluteHeight', 'AbsoluteMatrix', 'AbsoluteOpacity', 'AbsoluteRect', 'AbsoluteScale', 'AbsoluteToLocal', 'AbsoluteToLocalVector', 'AbsoluteWidth', 'ActionClient', 'AddFreeNotify', 'AddObject', 'AddObjectsToList', 'AdjustSizeValue', 'AdjustType', 'AfterConstruction', 'Align', 'Anchors', 'AniCalculations', 'AnimateColor', 'AnimateFloat', 'AnimateFloatDelay', 'AnimateFloatWait', 'AnimateInt', 'AnimateIntWait', 'ApplyStyleLookup', 'ApplyTriggerEffect', 'ApplyingEffect', 'Assign', 'AutoCalculateContentSize', 'AutoCapture', 'AutoHide', 'AutoTranslate', 'AxisAlignedRect', 'BeforeDestruction', 'BeginInvoke', 'BeginUpdate', 'BindMethodsToEvents', 'BottomRow', 'Bounces', 'BoundsRect', 'BringChildToFront', 'BringToFront', 'CanEdit', 'CanFocus', 'CanParentFocus', 'Canvas', 'CellByPoint', 'CellRect', 'Children', 'ChildrenCount', 'ChildrenRect', 'ClassInfo', 'ClassName', 'ClassNameIs', 'ClassParent', 'ClassType', 'CleanupInstance', 'ClearColumns', 'ClearContent', 'ClipChildren', 'ClipParent', 'ClipRect', 'Clone', 'Col', 'ColumnByIndex', 'ColumnByPoint', 'ColumnCount', 'ColumnIndex', 'ComObject', 'ComponentCount', 'ComponentIndex', 'ComponentState', 'ComponentStyle', 'Components', 'ContainsObject', 'Content', 'ContentBounds', 'ContentLayout', 'ContentSize', 'ControlType', 'Controls', 'ControlsCount', 'ConvertLocalPointFrom', 'ConvertLocalPointTo', 'Create', 'Cursor', 'CustomSceneAddRect', 'Data', 'DefaultDrawing', 'DefaultHandler', 'DefaultSize', 'DefaultStyleLookupName', 'DeleteChildren', 'DesignInfo', 'Destroy', 'DestroyComponents', 'Destroying', 'DisableDisappear', 'DisableFocusEffect', 'DisableMouseWheel', 'Dispatch', 'DisplayCells', 'DisposeOf', 'DragMode', 'EditorMode', 'EnableDragHighlight', 'Enabled', 'EnabledScroll', 'EndFunctionInvoke', 'EndInvoke', 'EndUpdate', 'EnumControls', 'EnumObjects', 'Equals', 'Exchange', 'ExecuteAction', 'FieldAddress', 'FindComponent', 'FindStyleResource', 'FixedSize', 'Free', 'FreeInstance', 'FreeNotification', 'FreeOnRelease', 'GetEnumerator', 'GetHashCode', 'GetInterface', 'GetInterfaceEntry', 'GetInterfaceTable', 'GetNamePath', 'GetParentComponent', 'GetTabList', 'GetUnusedViewportWidth', 'HScrollBar', 'HasAfterPaintEffect', 'HasClipParent', 'HasDisablePaintEffect', 'HasEffect', 'HasParent', 'Height', 'HelpContext', 'HelpKeyword', 'HelpType', 'Hint', 'HitTest', 'Images', 'InPaintTo', 'InViewRect', 'Index', 'Inflate', 'InheritedCursor', 'InheritsFrom', 'InitInstance', 'InsertComponent', 'InsertObject', 'InstanceSize', 'InvalidateRect', 'InvertAbsoluteMatrix', 'IsChild', 'IsDragOver', 'IsFocused', 'IsImplementorOf', 'IsInflated', 'IsMouseOver', 'IsUpdating', 'IsUsedInBinding', 'IsVisible', 'LeftColumn', 'LocalRect', 'LocalToAbsolute', 'LocalToAbsoluteVector', 'LocalToScreen', 'Lock', 'Locked', 'LookupStyleObject', 'MakeScreenshot', 'Margins', 'MethodAddress', 'MethodName', 'Model', 'Name', 'NeedStyleLookup', 'NewInstance', 'ObjectState', 'Observers', 'OnActivate', 'OnApplyStyleLookup', 'OnCalcContentBounds', 'OnCallbackGetValue', 'OnCanFocus', 'OnCellClick', 'OnCellDblClick', 'OnClick', 'OnColumnMoved', 'OnCreateCustomEditor', 'OnDblClick', 'OnDeactivate', 'OnDragDrop', 'OnDragEnd', 'OnDragEnter', 'OnDragLeave', 'OnDragOver', 'OnDrawColumnBackground', 'OnDrawColumnCell', 'OnDrawColumnHeader', 'OnEditingDone', 'OnEnter', 'OnExit', 'OnGesture', 'OnGetValue', 'OnHeaderClick', 'OnKeyDown', 'OnKeyUp', 'OnMouseDown', 'OnMouseEnter', 'OnMouseLeave', 'OnMouseMove', 'OnMouseUp', 'OnMouseWheel', 'OnPaint', 'OnPainting', 'OnResize', 'OnResized', 'OnSelChanged', 'OnSelectCell', 'OnSetValue', 'OnTap', 'OnViewportPositionChange', 'Opacity', 'Options', 'Owner', 'Padding', 'PaintTo', 'Parent', 'ParentClassStyleLookupName', 'ParentControl', 'ParentedRect', 'ParentedVisible', 'PointInObject', 'PointInObjectLocal', 'PopupMenu', 'Position', 'PrepareForPaint', 'Pressed', 'PressedPosition', 'QualifiedClassName', 'ReadOnly', 'RealignContent', 'RecalcAbsolute', 'RecalcAbsoluteNow', 'RecalcEnabled', 'RecalcHasClipParent', 'RecalcHasEffect', 'RecalcOpacity', 'RecalcSize', 'RecalcUpdateRect', 'ReferenceInterface', 'Release', 'Released', 'RemoveComponent', 'RemoveFreeNotification', 'RemoveFreeNotify', 'RemoveObject', 'Repaint', 'ResetFocus', 'RightColumn', 'Root', 'RotationAngle', 'RotationCenter', 'Row', 'RowByPoint', 'RowCount', 'RowHeight', 'SafeCallException', 'Scale', 'Scene', 'ScreenToLocal', 'ScrollAnimation', 'ScrollBy', 'ScrollDirections', 'ScrollTo', 'ScrollToCenter', 'ScrollToSelectedCell', 'ScrollToTop', 'SelectCell', 'SelectColumn', 'SelectRow', 'Selected', 'SendChildToBack', 'SendToBack', 'SetBounds', 'SetDesign', 'SetFocus', 'SetNewScene', 'SetProps', 'SetRoot', 'SetSubComponent', 'SetTopLeft', 'ShouldTestMouseHits', 'ShowHint', 'ShowInDesigner', 'ShowScrollBars', 'ShowSizeGrip', 'Size', 'Sort', 'StartTriggerAnimation', 'StartTriggerAnimationWait', 'StopPropertyAnimation', 'Stored', 'StyleLookup', 'StyleName', 'StyleState', 'StyledSettings', 'TabOrder', 'TabStop', 'Tag', 'TagFloat', 'TagObject', 'TagString', 'TextSettings', 'TextWidthToColWidth', 'ToList', 'ToString', 'ToTuple', 'TopRow', 'Touch', 'TouchTargetExpansion', 'TouchTracking', 'UnitName', 'UnitScope', 'UnloadPresentation', 'UpdateAction', 'UpdateContentSize', 'UpdateEffects', 'UpdateRect', 'VCLComObject', 'VScrollBar', 'ViewportPosition', 'ViewportSize', 'Visible', 'VisibleColumnCount', 'VisibleRows', 'Width', '__bound__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__owned__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

**Comment by lmbelo** [comment]
It seems we didn't wrapped it. I will investigate and in case we will take it to the roadmap.

**Comment by Priyatham10** [comment]
Will be testing this by creating a sample around the TStringGrid component

**Comment by lmbelo** [comment]
Sample ongoing.

**Comment by lmbelo** [comment]
Blocked due to TImageList dependency Embarcadero/python4delphi#68.
