### ISSUE TITLE
not working on synology

### ISSUE THREAD

**Issue by navy-git** [Embarcadero/DelphiFMX4Python#8]
Hello
When I want to execute the example controlsdemo.py on my synology NAS, I have an error in the import : 

Traceback (most recent call last):
  File "/volume1/py3/controlsdemo.py", line 12, in <module>
    from delphifmx import *
  File "/volume1/py3/delphifmx/__init__.py", line 82, in <module>
    package = new_import()
  File "/volume1/py3/delphifmx/__init__.py", line 68, in new_import
    modulefullpath = findmodule()
  File "/volume1/py3/delphifmx/__init__.py", line 65, in findmodule
    raise ValueError("Unsupported platform.")
ValueError: Unsupported platform.

Python3.10 it well detected.
It seems it is because the ossys is true detected as Linux but the libdir is None ???
Is there anything to do ?

Sorry for my bad english ... I'm french man
Thanks

**Comment by lmbelo** [comment]
Hi, @navy-git.

Can you run some code and share the outputs?

Run Python and execute the following, please:

1) import platform
2) print(platform.system())
3) print(platform.machine())

**Comment by navy-git** [comment]
another thing
When I use the expert in delphi to generate .py and .pydfm file, at the line :

self.LoadProps(os.path.join(os.path.dirname(os.path.abspath(__file__)), "Form1.pydfm"))

and I try to execute with pyscripter in windows there is an error :
Remote Server is not connected.
Please reinitialize or disconnect the remote interpreter 
and a button :              ABORT

When I use ToDoList.py it works fine but there is not the import of .pydfm file.

**Comment by lmbelo** [comment]
@navy-git unfortunately arm for Linux is not supported :/

**Comment by lmbelo** [comment]
Regarding your tests using PyScripter, I'll take notes and bring back to you.

**Comment by navy-git** [comment]
> @navy-git unfortunately arm for Linux is not supported :/

Ok thank you it's real a pity :o(

Regards
