### ISSUE TITLE
How can sub-forms be called up?

### ISSUE THREAD

**Issue by Rumia-Channel** [Embarcadero/DelphiFMX4Python#80]
Sub-forms with Main-form have been created in the Delphi application.
They were successfully exported, but no way to call the sub-forms from the main form was found.

These were exported successfully, but no way was found to call the sub-forms from the main form.

When MainWindow.py and Subwindow.py are exported, how to call them from MainWindow.py?

When I try to directly execute "self.Subwindow" in "__init__", which is written out by default, I get "TypeError: 'Form' object is not callable".

However, the documentation does not tell me how to create a Form other than MainForm.

How can I do this?

**Comment by Priyatham10** [comment]
Absolutely, you can do this with ease. Let me name here the MainWindow as `PrimaryWindow` and SubWindow as `SecondaryWindow`.

Important point to keep in mind:
- We can't export runtime code from the Delphi application. So, we need to implement this logic in the exported Python code files.

Let me create three code files here. I'm not using the Delphi application export but you can do this with that too..

## `main.py`
``` python
from delphifmx import *
from primary_window import PrimaryWindow

def main():
    Application.Initialize()
    Application.Title = 'Primary Window'
    Application.MainForm = PrimaryWindow(Application)
    Application.MainForm.Show()
    Application.Run()
    Application.MainForm.Destroy()

if __name__ == '__main__':
    main()
```

## primary_window.py
``` python
from delphifmx import *
from secondary_window import SecondaryWindow

class PrimaryWindow(Form):

    def __init__(self, owner):
        self.SetProps(Caption = "Primary Window")

        self.btn1 = Button(self)
        self.btn1.SetProps(
            Parent=self,
            Text="Button 1",
            Position=Position(PointF(20, 20)))

        self.btn2 = Button(self)
        self.btn2.SetProps(
            Parent=self,
            Text="Button 2",
            Position=Position(PointF(20, 60)))

        self.btn1.OnClick = self.btn1_on_click
        self.btn2.OnClick = self.btn2_on_click



    def btn1_on_click(self, Sender):
        self.secondary_window_obj = SecondaryWindow(self, button_text=self.btn1.Text)
        self.secondary_window_obj.Show()

    def btn2_on_click(self, Sender):
        self.secondary_window_obj = SecondaryWindow(self, button_text=self.btn2.Text)
        self.secondary_window_obj.Show()
```

## secondary_window.py
``` python
from delphifmx import *

class SecondaryWindow(Form):

    def __init__(self, owner, button_text):
        self.SetProps(Caption = "Secondary Window")

        self.back_btn = Button(self)
        self.back_btn.SetProps(
            Parent=self,
            Text="<---",
            Position=Position(PointF(20, 20)),
            OnClick=self.back_btn_click)

        self.lbl = Label(self)
        self.lbl.SetProps(
            Parent=self,
            Text=f"{button_text} is pressed",
            Position=Position(PointF(70, 70)))

    def back_btn_click(self, Sender):
        Application.MainForm.Show()
        self.Destroy()
```

You can see that we instantiated the `SecondaryWindow` using the kwargs (keyword arguments) in the `primary_window.py` :
![image](https://github.com/Embarcadero/DelphiFMX4Python/assets/17174106/5f8bce3f-6063-4f75-a213-4a2317d5bcb5)

Then used that kwargs in the `SecondaryWindow` initialization in it's `__inti__`:
![image](https://github.com/Embarcadero/DelphiFMX4Python/assets/17174106/9e9f2eee-1d45-44c7-85fb-34ec81c48be2)

And using this piece of code in `secondary_window.py`, we can close the `SecondaryWindow` and give the control back to `PrimaryWindow`:
![image](https://github.com/Embarcadero/DelphiFMX4Python/assets/17174106/ddf3e0e8-517f-418b-8132-8fbb622dee1b)

**Comment by Rumia-Channel** [comment]
This was my first "issue" and I apologise for not being used to writing them.
I didn't realise there was such a coding method!
I was able to solve the problem successfully!
Thank you so much for your help!
(using deepl)
